/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.jetbrains.dzaikov.diff;

import com.jetbrains.dzaikov.diff.analyzer.DiffAnalyzer;
import com.jetbrains.dzaikov.diff.analyzer.DiffStringsNumbersPair;
import com.jetbrains.dzaikov.diff.analyzer.DiffType;
import org.junit.After;
import org.junit.Before;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.TemporaryFolder;

import java.io.*;
import java.util.ArrayList;
import java.util.List;

import static org.junit.Assert.*;

public class AppTest {

    @Rule
    public TemporaryFolder folder= new TemporaryFolder();

    private String f1;
    private String f2;

    private void initFiles(String s1, String s2) throws IOException {
        File file1 = folder.newFile("test1.txt");
        BufferedWriter bw = new BufferedWriter(new FileWriter(file1));
        bw.write(s1);
        bw.flush();
        bw.close();
        f1 = file1.getAbsolutePath();
        File file2 = folder.newFile("test2.txt");
        bw = new BufferedWriter(new FileWriter(file2));
        bw.write(s2);
        bw.flush();
        bw.close();
        f2 = file2.getAbsolutePath();
    }

    @Test public void testEdited1() throws IOException {
        initFiles("1", "2");
        List<DiffStringsNumbersPair> diffExp = new ArrayList<>();
        diffExp.add(new DiffStringsNumbersPair(0, 0, DiffType.EDITED));
        assertEquals(diffExp, new DiffAnalyzer().getFilesDiff(f1, f2));
    }

    @Test public void testRemoved1() throws IOException {
        initFiles("1\n2", "2");
        List<DiffStringsNumbersPair> diffExp = new ArrayList<>();
        diffExp.add(new DiffStringsNumbersPair(0, -1, DiffType.REMOVED));
        diffExp.add(new DiffStringsNumbersPair(1, 0, DiffType.NONE));
        assertEquals(diffExp, new DiffAnalyzer().getFilesDiff(f1, f2));
    }

    @Test public void testAdded1() throws IOException {
        initFiles("1\n2", "1\n3\n2");
        List<DiffStringsNumbersPair> diffExp = new ArrayList<>();
        diffExp.add(new DiffStringsNumbersPair(0, 0, DiffType.NONE));
        diffExp.add(new DiffStringsNumbersPair(-1, 1, DiffType.ADDED));
        diffExp.add(new DiffStringsNumbersPair(1, 2, DiffType.NONE));
        assertEquals(diffExp, new DiffAnalyzer().getFilesDiff(f1, f2));
    }

    @Test public void testMixed1() throws IOException {
        initFiles("1\n2\n4\n5", "1\n3\n2\n6");
        List<DiffStringsNumbersPair> diffExp = new ArrayList<>();
        diffExp.add(new DiffStringsNumbersPair(0, 0, DiffType.NONE));
        diffExp.add(new DiffStringsNumbersPair(-1, 1, DiffType.ADDED));
        diffExp.add(new DiffStringsNumbersPair(1, 2, DiffType.NONE));
        diffExp.add(new DiffStringsNumbersPair(2, 3, DiffType.EDITED));
        diffExp.add(new DiffStringsNumbersPair(3, -1, DiffType.REMOVED));
        assertEquals(diffExp, new DiffAnalyzer().getFilesDiff(f1, f2));
    }
}
